### ISSUE TITLE
typescript types not present

### ISSUE THREAD

**Issue by z3r0d0n3** [yash-deore/react-ipfs-uploader#2]
hey, i tried using this with typescript but i get type errors  and this messages
Try `npm i --save-dev @types/react-ipfs-uploader`
while i'm figuring this out, maybe you guys could add those too
thank you

**Comment by yash-deore** [comment]
I know that it throws errors while using typescript. I will add typescript components in some time. 
As soon as I add the components I will close this issue.
Sorry for the inconvenience. 😔☹️

**Comment by z3r0d0n3** [comment]
thanks, i also noticed that multiple file uploader, when displaying the list of files, it shows some errors/warnings related to missing key attribute when mapping to show the list

**Comment by yash-deore** [comment]
Removed that too. If any more bugs or errors let me know.
