### ISSUE TITLE
Not working with Next.js

### ISSUE THREAD

**Issue by sadityakumar9211** [yash-deore/react-ipfs-uploader#3]
The is not working with Next.js. Just by importing it I keep getting this error.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/78147198/183086953-0dfd1b17-9ccf-4338-8947-93f66add5c33.png">

**Comment by umerarif01** [comment]
Same issue! Did you find the solution or any other alternative to upload data to ipfs? I was working with ipfsHttpClient but now it's giving me Gateway error

**Comment by yash-deore** [comment]
Please read the name of the library it is **_react_**-ipfs-uploader. I know it doesn't work with Next.js that's why I made it only for react.

**Comment by sadityakumar9211** [comment]
> Same issue! Did you find the solution or any other alternative to upload data to ipfs? I was working with ipfsHttpClient but now it's giving me Gateway error

Hey I have used `ipfs-core` library for uploading the files on ipfs . Just search for it on npm.
