### ISSUE TITLE
infura upgrade

### ISSUE THREAD

**Issue by iulianivg** [yash-deore/react-ipfs-uploader#4]
Infura has been upgraded and it's not possible to upload images via their public URLs. Users should now provide 

- project id (from infura IPFS)
- API key scret (from infura IPFS) 

We must update this package to do this

```
const auth = 'Basic ' + Buffer.from('user_project_id' + ':' + 'api_key_secret').toString('base64')
// this sets up the auth header to send 

var ipfs = ipfsHttpClient.create({
  host: 'ipfs.infura.io',
  port: 5001,
  protocol: 'https',
  apiPath:'/api/v0',
  headers: {
    authorization: auth
    }
});
```

**Comment by yash-deore** [comment]
Thanks for pointing that out, I couldn't find other alternatives so closing the package.
